apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: keenetic
      defaultBucket: keenetic
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: false
